# Generated by Django 2.0 on 2017-12-20 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='구매코드')),
                ('buy_edi_code', models.CharField(blank=True, default='', max_length=50, verbose_name='보험코드')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='시작일자')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='구매가격')),
                ('pay_type', models.CharField(blank=True, default='', max_length=50, verbose_name='급여구분')),
                ('pro_type', models.CharField(blank=True, default='', max_length=50, verbose_name='전문/일반')),
                ('active', models.BooleanField(default=True, verbose_name='사용중')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '구매정보',
                'verbose_name_plural': '구매정보',
                'ordering': ('-created',),
            },
            bases=(product.mixins.BuyInfoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='도매상명')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='팩스')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='메일')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '도매상',
                'verbose_name_plural': '도매상',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='제품명')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='제품코드')),
                ('edi_code', models.CharField(blank=True, default='', max_length=50, verbose_name='보험코드')),
                ('company', models.CharField(blank=True, default='', max_length=50, verbose_name='판매사')),
                ('std_unit', models.CharField(choices=[('TAB', 'TAB'), ('CAP', 'CAP'), ('VIAL', 'VIAL'), ('AMP', 'AMP'), ('BTL', 'BTL'), ('EA', 'EA'), ('ML', 'ML'), ('SYR', 'SYR'), ('BAG', 'BAG'), ('포', '포'), ('통', '통'), ('매', '매'), ('PEN', 'PEN'), ('G', 'G'), ('관', '관'), ('PKG', 'PKG'), ('POWD', 'POWD'), ('FILM', 'FILM'), ('KIT', 'KIT'), ('SC', 'SC'), ('GRAN', 'GRAN'), ('SET', 'SET'), ('IU', 'IU'), ('PFS', 'PFS'), ('SUPP', 'SUPP'), ('GEL', 'GEL'), ('TUBE', 'TUBE')], default='', max_length=10, verbose_name='제품규격')),
                ('pkg_amount', models.IntegerField(default=1, verbose_name='포장수량')),
                ('etc_class', models.CharField(choices=[('일반', '일반'), ('항암제', '항암제'), ('마약', '마약'), ('향정', '향정'), ('수액', '수액'), ('영양수액', '영양수액'), ('인슐린주사', '인슐린주사'), ('백신', '백신'), ('조영제', '조영제'), ('처치약품', '처치약품'), ('소모품', '소모품'), ('직송', '직송')], default='일반', max_length=10, verbose_name='기타구분')),
                ('apply_root', models.CharField(blank=True, default='', max_length=50, verbose_name='복용방법')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='적용단위')),
                ('unit_amount', models.CharField(blank=True, default='', max_length=50, verbose_name='규격단위량')),
                ('op_type', models.CharField(blank=True, default='', max_length=50, verbose_name='마약류구분')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='buyinfo',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Market'),
        ),
        migrations.AddField(
            model_name='buyinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
