# Generated by Django 2.0 on 2017-12-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinfo',
            name='edi_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='보험코드'),
        ),
        migrations.AddField(
            model_name='buyinfo',
            name='pay_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='급여구분'),
        ),
        migrations.AddField(
            model_name='buyinfo',
            name='pro_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='전문/일반'),
        ),
        migrations.AddField(
            model_name='product',
            name='apply_root',
            field=models.CharField(blank=True, max_length=50, verbose_name='복용방법'),
        ),
        migrations.AddField(
            model_name='product',
            name='op_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='마약류구분'),
        ),
        migrations.AddField(
            model_name='product',
            name='std_unit_amount',
            field=models.IntegerField(default=1, verbose_name='규격단위량'),
        ),
    ]
