# Generated by Django 2.0 on 2017-12-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171219_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='std_unit_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='적용단위'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_amount',
            field=models.CharField(blank=True, max_length=50, verbose_name='규격단위량'),
        ),
    ]
