# Generated by Django 2.0 on 2017-12-12 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='입고일자')),
                ('amount', models.IntegerField(verbose_name='입고수량')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buyitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.BuyItem')),
            ],
            options={
                'verbose_name': '입고기록',
                'verbose_name_plural': '입고기록',
                'ordering': ('-buyitemstock__created',),
            },
        ),
    ]
