# Generated by Django 2.0 on 2017-12-13 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_stockrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'ordering': ('-buyitem__created',), 'verbose_name': '입고기록', 'verbose_name_plural': '입고기록'},
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='입고일자'),
        ),
    ]
