# Generated by Django 2.0 on 2017-12-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_auto_20171213_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='입고일자'),
        ),
    ]
