# Generated by Django 2.0 on 2017-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_auto_20171213_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='입고수량'),
        ),
    ]
