# Generated by Django 2.0 on 2017-12-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_auto_20171215_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='buyitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buy.BuyItem'),
            preserve_default=False,
        ),
    ]
