# Generated by Django 2.0 on 2017-12-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0007_auto_20171215_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='buyinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.BuyInfo'),
        ),
    ]
